[project]
name = "de-hiring-take-home"
version = "0.1.0"
description = "ETL pipeline for Wikipedia data"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.31.0",
    "beautifulsoup4>=4.12.0",
    "bs4>=0.0.2",
]
